version: 2.1
setup: true
orbs:
  orb-tools: circleci/orb-tools@11.6.1
  shellcheck: circleci/shellcheck@3.1

filters: &all-tags
  tags:
    only: /.*/

jobs:
  # Execute a command from the orb and verify
  # the output is as expected
  #
  test-script:
    executor: gradle/default
    steps:
      - checkout
      - run:
          name: Test build file checksum
          command: |
                ./src/test/test_checksum_build_files.sh

workflows:
  lint-pack:
    jobs:
      - orb-tools/lint:
          filters: *all-tags
      - test-script:
          filters: *all-tags
      - orb-tools/pack:
          filters: *all-tags
      - orb-tools/review:
          filters: *all-tags
      - shellcheck/check:
          exclude: SC2148,SC2038,SC2086,SC2002,SC2016
          filters: *all-tags
      - orb-tools/publish:
          orb-name: entur/gradle-orb
          vcs-type: << pipeline.project.type >>
          requires:
            - orb-tools/lint
            - orb-tools/review
            - orb-tools/pack
            - shellcheck/check
            - test-script
          # Use a context to hold your publishing token.
          context: orb-publishing
          filters: *all-tags
          enable-pr-comment: false
      # Triggers the next workflow in the Orb Development Kit.
      - orb-tools/continue:
          pipeline-number: << pipeline.number >>
          vcs-type: << pipeline.project.type >>
          requires: [orb-tools/publish]
          filters: *all-tags
