version: 2.1
orbs:
  gradle: entur/gradle-orb@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.6.1
filters: &all-tags
  tags:
    only: /.*/
aliases:
  - &cache-key v2
jobs:
  # Execute a command from the orb and verify
  # the output is as expected
  #
  integration-test-cache:
    executor: gradle/default
    steps:
      - checkout
      - gradle/with_cache:
          - cache_key: *cache-key
          - steps:
              - run:
                  name: Check if Gradle wrapper and cache was saved and restored
                  command: |-
                    GRADLE_DIRECTORY="$HOME/.gradle"
                    if [[ ! -e $GRADLE_DIRECTORY ]]; then
                      echo "No gradle directory detected at $GRADLE_DIRECTORY"
                      exit 1
                    fi
                    GRADLE_CACHE_DIRECTORY="$GRADLE_DIRECTORY/caches"
                    if [[ ! -e $GRADLE_CACHE_DIRECTORY ]]; then
                      echo "No gradle cache directory detected at $GRADLE_CACHE_DIRECTORY"
                      exit 1
                    fi
                    GRADLE_WRAPPER_DIRECTORY="$GRADLE_DIRECTORY/wrapper"
                    if [[ ! -e $GRADLE_WRAPPER_DIRECTORY ]]; then
                      echo "No gradle wrapper directory detected at $GRADLE_WRAPPER_DIRECTORY"
                      exit 1
                    fi

workflows:
  test-deploy:
    jobs:
      - gradle/test:
          app_src_directory: sample_app
          reports_path: sample_app/build/reports/
          cache_key: *cache-key
          test_results_path: sample_app/build/test-results/
          wrapper_checksum_file: sample_app/gradle/wrapper/gradle-wrapper.properties
          filters: *all-tags
      - integration-test-cache:
          filters: *all-tags
          requires:
            - gradle/test
      - orb-tools/pack:
          filters: *all-tags
      - orb-tools/publish:
          orb-name: entur/gradle-orb
          vcs-type: << pipeline.project.type >>
          pub-type: production
          enable-pr-comment: false
          requires:
            - orb-tools/pack
            - integration-test-cache
            - gradle/test
          context: orb-publisher
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
